### PR TITLE
AVR backend bugfixes

### PR DESCRIPTION
**Pull request by gergoerdi**
This pull request is for tracking my commits that are unambiguously bugfixes. These don't introduce any new kludges, don't ignore any known corner cases, etc.

### CODE REVIEW

**Comment by dylanmckay** [comment]
This looks really nice!

The only thing I'm questioning is the way you've implemented relaxed branches. A new node has been added, which you have to explicitly use to opt-into branch relaxation. I believe this is quite a strange way of implementing this.

I haven't looked into this specific area much, and so I am not much help. I've been told in the past that we should use the "target-independent branch relaxation pass" for AVR, and so I definitely lean in that direction.

I'd rather reinstate the old `AVRBSel` pass which did the relaxation that introduce new nodes which also regress performance (trampolines are always inserted).

**Comment by dylanmckay** [comment]
Also, did you want me to upstream the rest of the commits? Thanks for these by the way!

**Comment by gergoerdi** [comment]
It is not clear yet how this could be integrated into LLVM's relaxation framework, since it doesn't seem to allow generating pseudo-instructions: https://stackoverflow.com/q/43763201/477476

**Comment by gergoerdi** [comment]
Please go on with upstreaming the rest of the commits.

**Comment by dylanmckay** [comment]
I've checked the commit list and every commit in this PR except for "[AVR] Add pseudo-instructions for relaxed branches." has already been merged and upstreamed to LLVM proper.

The only non-upstreamed commit is very hacky, plus I've properly enabled the branch selector for AVR in upstream commit r307617, so the problem there is now fixed anyway.

Closing this

**Pull request closed without merging**
